<?php

namespace Database\Seeders;

use App\Models\User;
use App\Models\Property;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $this->command->info('🏠 Seeding properties with detailed information...');

        // Get host users
        $hosts = User::where('is_host', true)->get();
        
        if ($hosts->isEmpty()) {
            $this->command->warn('⚠️ No host users found. Please seed users first.');
            return;
        }

        // Detailed Gambia properties with all required fields
        $propertiesData = [
            // Beachfront Villas
            [
                'host_id' => $hosts->random()->id,
                'title' => 'Ocean Breeze Beach Villa',
                'description' => 'Stunning 4-bedroom beachfront villa with direct beach access. Wake up to the sound of waves and enjoy breathtaking sunset views. Features a private pool, fully equipped kitchen, and spacious terraces overlooking the Atlantic Ocean. Perfect for families or groups looking for paradise.',
                'property_type' => 'villa',
                'gambia_category' => 'beachfront_villa',
                'address' => 'Kotu Beach Road',
                'city' => 'Kotu',
                'country' => 'Gambia',
                'latitude' => 13.4278,
                'longitude' => -16.6789,
                'guest_capacity' => 8,
                'bedrooms' => 4,
                'beds' => 5,
                'bathrooms' => 3,
                'base_price' => 280,
                'cleaning_fee' => 50,
                'weekly_discount' => 10,
                'monthly_discount' => 20,
                'extra_guest_fee' => 20,
                'security_deposit' => 200,
                'images' => json_encode(['villas/ocean-breeze-1.jpg', 'villas/ocean-breeze-2.jpg']),
                'amenities' => json_encode(['wifi', 'pool', 'ac', 'kitchen', 'parking', 'beach_access', 'sea_view', 'garden', 'cctv', 'security_guard']),
                'is_active' => true,
                'verified_listing' => true,
                'quality_score' => 4.9,
                'min_nights' => 2,
                'max_nights' => 30,
                'instant_book' => true,
                'self_check_in' => true,
                'check_in_time' => '14:00',
                'check_out_time' => '11:00',
                'cancellation_policy' => 'moderate',
                'house_rules' => 'No smoking indoors. Quiet hours after 10 PM. No parties without prior approval.',
            ],
            [
                'host_id' => $hosts->random()->id,
                'title' => 'Sunset Cove Holiday Home',
                'description' => 'Charming 3-bedroom home steps from the beach. Known for incredible sunset views and proximity to local restaurants. Air conditioning in all rooms, hot water, and reliable WiFi. Our friendly local staff can arrange tours and airport transfers.',
                'property_type' => 'house',
                'gambia_category' => 'beachfront_villa',
                'address' => 'Kololi Beach Strip',
                'city' => 'Kololi',
                'country' => 'Gambia',
                'latitude' => 13.4167,
                'longitude' => -16.7500,
                'guest_capacity' => 6,
                'bedrooms' => 3,
                'beds' => 4,
                'bathrooms' => 2,
                'base_price' => 150,
                'cleaning_fee' => 30,
                'weekly_discount' => 15,
                'monthly_discount' => 25,
                'extra_guest_fee' => 15,
                'security_deposit' => 100,
                'images' => json_encode(['villas/sunset-cove-1.jpg']),
                'amenities' => json_encode(['wifi', 'ac', 'kitchen', 'parking', 'beach_access', 'security_guard', 'garden']),
                'is_active' => true,
                'verified_listing' => true,
                'quality_score' => 4.7,
                'min_nights' => 1,
                'max_nights' => 30,
                'instant_book' => true,
                'self_check_in' => false,
                'check_in_time' => '15:00',
                'check_out_time' => '11:00',
                'cancellation_policy' => 'flexible',
                'house_rules' => 'Respect our neighbors. No loud music after 9 PM.',
            ],
            // Eco Lodges
            [
                'host_id' => $hosts->random()->id,
                'title' => 'Makasutu Forest Eco Lodge',
                'description' => 'Immerse yourself in nature at our sustainable eco-lodge surrounded by Makasutu Nature Park. Solar-powered, organic gardens, and wildlife sightings including monkeys and exotic birds. Experience off-grid living with modern comforts. Community tours and cultural experiences available.',
                'property_type' => 'cottage',
                'gambia_category' => 'eco_lodge',
                'address' => 'Makasutu Village',
                'city' => 'Brikama',
                'country' => 'Gambia',
                'latitude' => 13.2333,
                'longitude' => -16.5500,
                'guest_capacity' => 4,
                'bedrooms' => 2,
                'beds' => 3,
                'bathrooms' => 1,
                'base_price' => 85,
                'cleaning_fee' => 15,
                'weekly_discount' => 20,
                'monthly_discount' => 30,
                'extra_guest_fee' => 10,
                'security_deposit' => 50,
                'images' => json_encode(['eco/makasutu-1.jpg', 'eco/makasutu-2.jpg']),
                'amenities' => json_encode(['wifi', 'kitchen', 'garden', 'parking', 'terrace', 'bbq']),
                'is_active' => true,
                'verified_listing' => true,
                'quality_score' => 4.8,
                'min_nights' => 2,
                'max_nights' => 14,
                'instant_book' => false,
                'self_check_in' => true,
                'check_in_time' => '12:00',
                'check_out_time' => '10:00',
                'cancellation_policy' => 'moderate',
                'house_rules' => 'Leave no trace. Respect wildlife. Community guidelines provided on arrival.',
            ],
            // Cultural Homestays
            [
                'host_id' => $hosts->random()->id,
                'title' => 'Authentic Gambian Family Homestay',
                'description' => 'Experience real Gambian hospitality in our family home. Share meals with your host family, learn to cook traditional dishes, and immerse yourself in local culture. Walking distance to markets and public transport. Perfect for cultural immersion seekers.',
                'property_type' => 'entire_place',
                'gambia_category' => 'cultural_homestay',
                'address' => 'Bakau New Town',
                'city' => 'Bakau',
                'country' => 'Gambia',
                'latitude' => 13.4719,
                'longitude' => -16.6781,
                'guest_capacity' => 2,
                'bedrooms' => 1,
                'beds' => 1,
                'bathrooms' => 1,
                'base_price' => 35,
                'cleaning_fee' => 5,
                'weekly_discount' => 10,
                'monthly_discount' => 20,
                'extra_guest_fee' => 10,
                'security_deposit' => 0,
                'images' => json_encode(['homestay/family-home-1.jpg']),
                'amenities' => json_encode(['wifi', 'kitchen', 'running_water', 'electricity']),
                'is_active' => true,
                'verified_listing' => true,
                'quality_score' => 4.6,
                'min_nights' => 3,
                'max_nights' => 60,
                'instant_book' => false,
                'self_check_in' => false,
                'check_in_time' => '08:00',
                'check_out_time' => '20:00',
                'cancellation_policy' => 'flexible',
                'house_rules' => 'Remove shoes indoors. Participate in family meals (optional). Respect cultural norms.',
            ],
            // Urban Apartments
            [
                'host_id' => $hosts->random()->id,
                'title' => 'Modern Serekunda Studio Apartment',
                'description' => 'Clean and comfortable studio apartment in the heart of Serekunda. Walking distance to supermarkets, banks, and restaurants. Perfect for business travelers or couples looking for a convenient base to explore The Gambia.',
                'property_type' => 'apartment',
                'gambia_category' => 'urban_apartment',
                'address' => 'Kairaba Avenue',
                'city' => 'Serekunda',
                'country' => 'Gambia',
                'latitude' => 13.4333,
                'longitude' => -16.6833,
                'guest_capacity' => 2,
                'bedrooms' => 1,
                'beds' => 1,
                'bathrooms' => 1,
                'base_price' => 55,
                'cleaning_fee' => 10,
                'weekly_discount' => 15,
                'monthly_discount' => 25,
                'extra_guest_fee' => 10,
                'security_deposit' => 50,
                'images' => json_encode(['apartments/modern-studio-1.jpg']),
                'amenities' => json_encode(['wifi', 'ac', 'kitchen', 'parking', 'cctv', 'running_water', 'electricity']),
                'is_active' => true,
                'verified_listing' => true,
                'quality_score' => 4.5,
                'min_nights' => 1,
                'max_nights' => 90,
                'instant_book' => true,
                'self_check_in' => true,
                'check_in_time' => '14:00',
                'check_out_time' => '12:00',
                'cancellation_policy' => 'moderate',
                'house_rules' => 'No smoking. Keep noise levels reasonable.',
            ],
            // Guest Houses
            [
                'host_id' => $hosts->random()->id,
                'title' => 'Gunjur Garden Guest House',
                'description' => 'Peaceful guest house in Gunjur with beautiful tropical gardens. Close to Gunjur Beach and the Tanji Bird Reserve. Home-cooked meals available. Perfect for nature lovers and bird watchers.',
                'property_type' => 'house',
                'gambia_category' => 'guest_house',
                'address' => 'Gunjur Main Street',
                'city' => 'Gunjur',
                'country' => 'Gambia',
                'latitude' => 13.2833,
                'longitude' => -16.7500,
                'guest_capacity' => 4,
                'bedrooms' => 2,
                'beds' => 2,
                'bathrooms' => 1,
                'base_price' => 65,
                'cleaning_fee' => 10,
                'weekly_discount' => 15,
                'monthly_discount' => 25,
                'extra_guest_fee' => 10,
                'security_deposit' => 50,
                'images' => json_encode(['guesthouse/gunjur-garden-1.jpg']),
                'amenities' => json_encode(['wifi', 'kitchen', 'garden', 'parking', 'terrace', 'bbq', 'running_water']),
                'is_active' => true,
                'verified_listing' => true,
                'quality_score' => 4.4,
                'min_nights' => 2,
                'max_nights' => 30,
                'instant_book' => false,
                'self_check_in' => false,
                'check_in_time' => '12:00',
                'check_out_time' => '11:00',
                'cancellation_policy' => 'moderate',
                'house_rules' => 'Garden access available. Bird watching tours can be arranged.',
            ],
            // Traditional Compounds
            [
                'host_id' => $hosts->random()->id,
                'title' => 'Fajikunda Traditional Compound',
                'description' => 'Authentic Gambian compound living experience. Stay in a traditional circular hut with modern amenities. Your host family will share their daily life, traditions, and local knowledge. An unforgettable cultural experience.',
                'property_type' => 'entire_place',
                'gambia_category' => 'traditional_compound',
                'address' => 'Fajikunda Compound',
                'city' => 'Fajikunda',
                'country' => 'Gambia',
                'latitude' => 13.4500,
                'longitude' => -16.6000,
                'guest_capacity' => 2,
                'bedrooms' => 1,
                'beds' => 1,
                'bathrooms' => 1,
                'base_price' => 25,
                'cleaning_fee' => 5,
                'weekly_discount' => 15,
                'monthly_discount' => 25,
                'extra_guest_fee' => 5,
                'security_deposit' => 0,
                'images' => json_encode(['compound/traditional-1.jpg']),
                'amenities' => json_encode(['running_water', 'electricity', 'kitchen']),
                'is_active' => true,
                'verified_listing' => true,
                'quality_score' => 4.3,
                'min_nights' => 7,
                'max_nights' => 90,
                'instant_book' => false,
                'self_check_in' => false,
                'check_in_time' => '08:00',
                'check_out_time' => '20:00',
                'cancellation_policy' => 'flexible',
                'house_rules' => 'Remove shoes indoors. Participate in daily activities (optional). Respect family privacy.',
            ],
            // River Lodges
            [
                'host_id' => $hosts->random()->id,
                'title' => 'Marakissa River Lodge',
                'description' => 'Peaceful riverside accommodation overlooking the Marakissa River. Known for excellent bird watching and river cruises. Fresh water swimming, fishing, and nature walks available. Remote and tranquil setting perfect for relaxation.',
                'property_type' => 'cottage',
                'gambia_category' => 'river_lodge',
                'address' => 'Marakissa Village',
                'city' => 'Marakissa',
                'country' => 'Gambia',
                'latitude' => 13.3167,
                'longitude' => -16.4167,
                'guest_capacity' => 6,
                'bedrooms' => 3,
                'beds' => 4,
                'bathrooms' => 2,
                'base_price' => 95,
                'cleaning_fee' => 20,
                'weekly_discount' => 15,
                'monthly_discount' => 25,
                'extra_guest_fee' => 15,
                'security_deposit' => 75,
                'images' => json_encode(['river/marakissa-1.jpg', 'river/marakissa-2.jpg']),
                'amenities' => json_encode(['wifi', 'kitchen', 'garden', 'parking', 'terrace']),
                'is_active' => true,
                'verified_listing' => true,
                'quality_score' => 4.6,
                'min_nights' => 2,
                'max_nights' => 21,
                'instant_book' => false,
                'self_check_in' => true,
                'check_in_time' => '12:00',
                'check_out_time' => '10:00',
                'cancellation_policy' => 'moderate',
                'house_rules' => 'Respect river wildlife. Kayak and boat rentals available. No jet skis.',
            ],
        ];

        // Create all properties
        $created = 0;
        foreach ($propertiesData as $data) {
            Property::updateOrCreate(
                ['title' => $data['title'], 'host_id' => $data['host_id']],
                $data
            );
            $created++;
        }

        $this->command->info("✅ Created {$created} detailed properties with full information!");
        $this->command->info('');
        $this->command->info('📍 Property categories included:');
        $this->command->info('   - Beachfront Villas: 2');
        $this->command->info('   - Eco Lodge: 1');
        $this->command->info('   - Cultural Homestay: 1');
        $this->command->info('   - Urban Apartment: 1');
        $this->command->info('   - Guest House: 1');
        $this->command->info('   - Traditional Compound: 1');
        $this->command->info('   - River Lodge: 1');
    }
}
